# Generated by Django 4.2.7 on 2024-02-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGRS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('complaint', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to='complaint_proof/')),
            ],
        ),
    ]
