# Generated by Django 4.2.7 on 2024-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGRS_app', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
