# Generated by Django 4.2.7 on 2024-02-04 10:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGRS_app', '0003_complaint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reg_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='new_reg',
            name='reg_no',
            field=models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
