# Generated by Django 4.2.7 on 2024-02-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGRS_app', '0004_alter_complaint_reg_no_alter_new_reg_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
