# Generated by Django 4.2.7 on 2024-02-05 06:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGRS_app', '0005_staff_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_reg',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='staff_reg',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
