# Generated by Django 4.2.7 on 2024-02-05 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CGRS_app', '0006_staff_reg_password_staff_reg_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_reg',
            name='username',
        ),
        migrations.AddField(
            model_name='staff_reg',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
