# Generated by Django 4.2.7 on 2024-02-05 12:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGRS_app', '0008_staffreg_delete_staff_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffreg',
            name='user',
        ),
        migrations.AddField(
            model_name='staffreg',
            name='c_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffreg',
            name='email',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffreg',
            name='name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffreg',
            name='reg_no',
            field=models.CharField(default='', max_length=200, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
